name: Deploy to Tsuru

on:
  push:
    branches:
      - main  # Trigger on push to the main branch. Change this as needed.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Install Tsuru CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/tsuru/tsuru-client/master/install.sh | sh
          echo "Tsuru CLI installed"

      - name: Add Target
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
          TSURU_HOST: ${{ secrets.TSURU_HOST }}
        run: |
          tsuru target-add default $TSURU_HOST -s

      - name: Rename war file
        run: |
          mv ./build/libs/PatientServer-1.0-SNAPSHOT.war ./ROOT.war

      - name: Set Tsuru Environment Variables
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
        run: |
          tsuru env-set -a bioeng-fguys-app SMTP_HOST=$SMTP_HOST
          tsuru env-set -a bioeng-fguys-app SMTP_PORT=$SMTP_PORT
          tsuru env-set -a bioeng-fguys-app SMTP_USERNAME=$SMTP_USERNAME
          tsuru env-set -a bioeng-fguys-app SMTP_PASSWORD=$SMTP_PASSWORD
          tsuru env-set -a bioeng-fguys-app APP_BASE_URL=$APP_BASE_URL
      
      - name: Deploy to Tsuru
        env:
          TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
        run: |
          tsuru app-deploy -a bioeng-fguys-app ROOT.war
